### ISSUE TITLE
Function setMinDelays shouldnt require ordered amounts

### ISSUE THREAD

**Issue by ashwinarora** [The-Poolz/DelayVault#87]
Issue ID
DV-3

Risk level
Severity: Medium, Likelihood: Medium

Description
The function setMinDelays requires that input parameters _amounts is an ordered array along with _startDelays, _cliffDelays, and _finishDelays. However, for a token release, it is not logical to require that a higher delay would be corresponding to a higher unlocked token amount. 
This issue should also be addressed in the function CreateVault, which calls the function GetMinDelays that is based on the input parameter amount.

Recommendation
There is no need to require the _amounts parameter to be ordered as the timing parameters. The _orderedArrays function should only check the timing parameters _startDelays, _cliffDelays, and _finishDelays as ordered arrays.

**Comment by Lomet** [comment]
I think only the amount needs to be ordered. so we can check the first amount that is > then the amount that the user inputs.
in future. we may do that after a bigger amount. you get some lower cooldown. or lower cliff time.

**Comment by Lomet** [comment]
for example use case:
up to 250 poolz tokens - its a week start time (finish=clif=0)
up to 1000 tokens - its 2-week start time
up to 20000 tokens. its 4 weeks start time
up to 50000, its 0 start time, 3 month finish time with 1-month cliff
and up to 100000 and above its 0 start time, 4 month finish time with 0 cliff

**Comment by YouStillAlive** [comment]
I think the current logic(in master) implements the case where the sorted only amounts.

Tests that prove it: https://github.com/The-Poolz/Integrate/blob/integrate-v2/test/DelayVault.js#L19-L25

Can we remove these lines? https://github.com/The-Poolz/DelayVault/blob/5fce42ac4865fe170d34afb22c315aaf996e5b11/contracts/DelayView.sol#L75-L77

**Comment by YouStillAlive** [comment]
Decided that only amounts needed to be sorted. FinishTime, StartTime, CliffTime may not be sorted in the limits array.
closes by #94
