### ISSUE TITLE
Gas optimizations

### ISSUE THREAD

**Issue by ashwinarora** [The-Poolz/DelayVault#89]
Issue ID
DV-5

Risk level
Severity: Low, Likelihood: High

Description
In DelayVault.sol file, it can be optimized by using a mapping for the _token and msg.sender for easier check of existence
delayLimit.Amounts.length could be replaced by using a parameter for the length to avoid re-reading length in every iteration.

**Comment by YouStillAlive** [comment]
We can add a new boolean struct field to Vault and use it for optimization: https://github.com/The-Poolz/DelayVault/pull/96

If we set Amount/StartDelay/CliffDelay/FinishDelay > 0, after removing and re-locking tokens, a duplicate will appear in the Users[_token] array.

I like the solution we already have, but it's not a very big change.

**Comment by Lomet** [comment]
I think we can close it, @ashwinarora what do you think?

**Comment by YouStillAlive** [comment]
delayLimit.Amounts.length is now stored in a local variable. The existence of an array element is now checked using the helper function `addIfNotExsist`. 
closed #92 and #94
